
  portaineraudrey:
    restart: always
    image: portainer/portainer
    container_name: portaineraudrey
    ports:
      - 9000:9000
    volumes:
      - /home/audrey/dockers/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true