  sickrage-%USER%:
    restart: always
    image: xataz/sickrage
    container_name: sickrage-%USER%
    environment:
      - UID=%UID%
      - GID=%GID%
      - WEBROOT=/sickrage
    volumes:
     - /home/%USER%/torrents:/data/torrents
     - /home/%USER%/watch:/data/.watch
     - /home/%USER%/dockers/sickrage/data:/data
     - /home/%USER%/dockers/sickrage/config:/config
