
  couchpotato-%USER%:
    restart: always
    image: xataz/couchpotato
    container_name: couchpotato-%USER%
    environment:
      - UID=%UID%
      - GID=%GID%
      - WEBROOT=/couchpotato
    volumes:
     - /home/%USER%/watch:/root
     - /home/%USER%/dockers/couchpotato/config:/config
